Analytics_Coforge:
  outputs:
    dev:
      account: RFXWNNW-QWB07245
      database: Test_Analytics
      password: Sachin@10
      role: analyticsengineer
      schema: dbt_mkt
      threads: 3
      type: snowflake
      user: Sachin
      warehouse: transform_wh
  target: dev
