version: 2

models:
  - name: stg_customers
  - name: stg_nations
    config:
      group: apple
      access: public
    description: Staging table for all the nations 
    columns:
      - name: nation_id
        description: Primary key for the NATIONS table
        tests:
          - unique:
              config:
                store_failures: true
                schema: dbt_test_failures
                store_failures_as: view
          - not_null:
              config:
                store_failures: true
                schema: dbt_test_failures
      - name: region_id
        description: Foreign Key from REGION table
        tests:
          - relationships:
              field: region_id
              to: ref('stg_regions')
              config:
                store_failures: true
  - name: stg_regions
    config:
      group: orange
      access: public
    description: '{{ doc("overview")}}'
    columns:
      - name: region_id
        description: '{{ doc("pkey")}}'
      - name: name
        tests:
          - accepted_values:
              values:
                - "AFRICA"
                - "AMERICA"
                - "ASIA"
                - "EUROPE"
                - "MIDDLE EAST"
          - dbt_utils.not_accepted_values:
              values: ["NewRegion", "OldRegion"]
groups:
  - name: apple
    owner: 
      name: MKT
  - name: orange
    owner: 
      name: Murali

seeds:
  - name: supplier_names
    config:
      alias: real_suppliers